version: '3.9'
services:
  db:
    image: 'docker.io/library/mariadb:10.3'
    hostname: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "mypassword"
    healthcheck:
      test: "/usr/bin/mysql --user=test --password=test --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/1.sql"